### ISSUE TITLE
Pi 5 support

### ISSUE THREAD

**Issue by bobfiggs** [davidmpye/V10_Dyson_BMS#16]
Hi David,

Great project!

I have followed your flashing Wiki. I am using a Pi5 and I am getting an error that the installed operating system does not indicate support for Raspberry Pi 5.  
Any suggestions?

Thank you
Bob

**Comment by davidmpye** [comment]
Hi Bob,

Where are you seeing this error?

I haven't built or tested with a pi5 so you are a bit ahead of the curve

David

**Comment by bobfiggs** [comment]
David,

Thanks for the quick response.  

I get notification on boot up of the Pi. Please see attached.

I have tried editing the config file with the os_check=0 but then the pi does nothing on boot.  No video, the onboard LED just stays solid green. 

Bob

![20240923_112057](https://github.com/user-attachments/assets/f9a701c3-51f1-4e34-ada6-cc1d5cb998b6)

**Comment by bobfiggs** [comment]
David,

Got a rpi zero and used v1.2, battery now works!

Thanks for sharing!
