### ISSUE TITLE
Version of V10 battery with different pinout

### ISSUE THREAD

**Issue by andrea86re** [davidmpye/V10_Dyson_BMS#5]
Hello and thanks for your sharing.
I have recently attempted in fixing a V10 failed with red flashes. I found out there was one of the batteries in short. I replaced the batteries and I am now in the need of refleashing the controller.

However, my board is different than the one you have shown.
There is a smaller 6-pins interface, w/o any text written on the board.

The microcontroller in this case is:
essemi ES7P0693FHTF

I attatch the pics of the board.
Could you confirm that you have no experience with such a version, so no fixing possible?

Thank you,
Andrea
![1703593985561](https://github.com/davidmpye/V10_Dyson_BMS/assets/154893051/3c07ecf2-b402-4a06-91d6-39f36f0dd8ed)
![1703593985569](https://github.com/davidmpye/V10_Dyson_BMS/assets/154893051/4f89efa7-4f51-4de6-be90-d7f5091c0ad6)

**Comment by davidmpye** [comment]
Hi!

This board is not a Dyson original - it's one of the Chinese 'replacement'
batteries.

Therefore I am afraid there's nothing I can offer.

However it is quite likely it might be happy with you replacing the cell,
as long as the board isn't damaged.

David
