### ISSUE TITLE
Not working on Raspberry Pi 2 Model B

### ISSUE THREAD

**Issue by bumaociyuan** [davidmpye/V10_Dyson_BMS#6]
Hi David,

I have followed [flashing-with-a-raspberry-pi-as-the-programmer](https://github.com/davidmpye/V10_Dyson_BMS/wiki/Flashing#flashing-with-a-raspberry-pi-as-the-programmer) with release v1.0.1 but not working.
Here are the connection photos and error log:

![IMG_3465 copy](https://github.com/davidmpye/V10_Dyson_BMS/assets/4977911/5dc1e333-cd44-4b58-872b-0384d5f822f3)
![IMG_3466 copy](https://github.com/davidmpye/V10_Dyson_BMS/assets/4977911/46b800bb-9deb-4bda-99ac-355d2da77306)
![IMG_3467 copy](https://github.com/davidmpye/V10_Dyson_BMS/assets/4977911/512ad023-4be9-485b-83fe-35048ebee67f)

* https://github.com/davidmpye/V10_Dyson_BMS/issues/1#issuecomment-1750217872 I have tried replace V10_BMS.elf of this link. But not working.
*  I continuously clicked the black button, but it still didn't work.

**Comment by davidmpye** [comment]
Hi,

The most common problem is a connection issue.

The pin header on the battery PCB is covered with a clear insulating
lacquer (including inside the holes) so you'll need to remove this.

Ideally the best option is just to remove it mechanically with a fibreglass
pencil and solder the wires to the pads to guarantee a good connection.

The errors you show are just "connection errors" so I can't debug any
further than that - sorry.

Best wishes

David
